export const Projects = [
   {title: 'Share Shed',
    tech: 'Node, MySQL',
    deployedLink: 'https://obscure-woodland-19082.herokuapp.com/',
    github: 'https://github.com/wolldog/share-shed',
    image: '../../assets/Images/share-shed.jpg',
    },
    {title: 'Share Shed',
    tech: 'Node, MySQL',
    deployedLink: 'https://obscure-woodland-19082.herokuapp.com/',
    github: 'https://github.com/wolldog/share-shed',
    image: '../../assets/Images/share-shed.jpg',
    },
    {title: 'Share Shed',
    tech: 'Node, MySQL',
    deployedLink: 'https://obscure-woodland-19082.herokuapp.com/',
    github: 'https://github.com/wolldog/share-shed',
    image: '../../assets/Images/share-shed.jpg',
    },
    {title: 'Share Shed',
    tech: 'Node, MySQL',
    deployedLink: 'https://obscure-woodland-19082.herokuapp.com/',
    github: 'https://github.com/wolldog/share-shed',
    image: '../../assets/Images/share-shed.jpg',
    },
    {title: 'Share Shed',
    tech: 'Node, MySQL',
    deployedLink: 'https://obscure-woodland-19082.herokuapp.com/',
    github: 'https://github.com/wolldog/share-shed',
    image: '../../assets/Images/share-shed.jpg',
    }
]