export const Projects = [
  {
    id: "1",
    title: "Share Shed",
    tech: "Node, MySQL",
    description:
      "Enables users to earn a rental income from tools they own but only use occasionally.",
    deployedLink: "https://obscure-woodland-19082.herokuapp.com/",
    github: "https://github.com/wolldog/share-shed",
    image: "share-shed",
    alt: "A Parako chainsaw spray painted on a a wall",
  },
  {
    id: "2",
    title: "Weather Or Not",
    tech: "JavaScript, Bootstrap",
    description:
      "A 5 day weather forecast dashboard application using the third-party API Openweathermap.",
    deployedLink: "https://wolldog.github.io/weather-or-not/",
    github: "https://github.com/wolldog/weather-or-not",
    image: "weatherOrNot",
    alt: "A sun partially covered by a cloud painted in yellow on a grey wall",
  },
  {
    id: "3",
    title: "Spoof Social",
    tech: "JavaScript",
    description: "An API for a social networking web application (video demo)",
    deployedLink: "https://watch.screencastify.com/v/4FjBTkkKpFBRZIFhniEr",
    github: "https://github.com/wolldog/spoof_social",
    image: "spoof-social",
    alt: "Banksie style artwork of child's siloette holding a bunch of colourful balloons depicting social media logos",
  },
  {
    id: "4",
    title: "Take Note",
    tech: "JavaScript",
    description: "A simple but effective note taking application.",
    deployedLink: "https://agile-cliffs-83755.herokuapp.com/notes",
    github: "https://github.com/wolldog/take-note",
    image: "take-note",
    alt: "A blue, pink and orange mural with the words 'I will never forget you!",
  },
  {
    id: "5",
    title: "Plate Pals",
    tech: "Node, MySQL",
    description:
      "Simple food and cocktail recipes from around the world to try out with your friends.",
    deployedLink: "https://obscure-woodland-19082.herokuapp.com/",
    github: "https://github.com/wolldog/share-shed",
    image: "plate-pals",
    alt: "A colourful mural painted on a wall depicting a 3 patty burger with eyes and a moustache",
  },
  {
    id: "6",
    title: "BlogIT",
    tech: "Node, MySQL",
    description:
      "A CMS-style blog site where developers can publish their thoughts and ideas.",
    deployedLink: "https://powerful-plateau-20197.herokuapp.com/",
    github: "https://github.com/wolldog/blogIT",
    image: "blog-IT",
    alt: "Two speech bubbles painted in dripping black paint on a white wall",
  },
];
